title: Hwa Jin Choi
email: a01045960620@gmail.com
url: "https://hwajinchoi.github.io/Home/"
baseurl: "/Home"
repository: "https://github.com/HwajinChoi/Home"

author:
  name  : "Hwa Jin Choi"
  avatar : ""
  location : "Korea"
  email :
  links :
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:a01045960620email.com  
# Build settings
theme: jekyll-theme-minimal
